go test github.com/chyroc/go-redis -coverprofile=coverage.out -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal -coverprofile=coverage.out.2 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/basetype -coverprofile=coverage.out.3 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/database -coverprofile=coverage.out.4 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/helper -coverprofile=coverage.out.5 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/helper/gr-binary -coverprofile=coverage.out.6 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/helper/ints -coverprofile=coverage.out.7 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/logger -coverprofile=coverage.out.8 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/objects -coverprofile=coverage.out.9 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/proto-resp -coverprofile=coverage.out.10 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/resp -coverprofile=coverage.out.11 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/server -coverprofile=coverage.out.12 -covermode=count -coverpkg=./...
go test github.com/chyroc/go-redis/internal/tests -coverprofile=coverage.out.13 -covermode=count -coverpkg=./...

tail -n +2 coverage.out.2 >> coverage.out
tail -n +2 coverage.out.3 >> coverage.out
tail -n +2 coverage.out.4 >> coverage.out
tail -n +2 coverage.out.5 >> coverage.out
tail -n +2 coverage.out.6 >> coverage.out
tail -n +2 coverage.out.7 >> coverage.out
tail -n +2 coverage.out.8 >> coverage.out
tail -n +2 coverage.out.9 >> coverage.out
tail -n +2 coverage.out.10 >> coverage.out
tail -n +2 coverage.out.11 >> coverage.out
tail -n +2 coverage.out.12 >> coverage.out
tail -n +2 coverage.out.13 >> coverage.out

go tool cover -html coverage.out -o coverage.html

rm coverage.out.10
rm coverage.out.11
rm coverage.out.12
rm coverage.out.13
rm coverage.out.2
rm coverage.out.3
rm coverage.out.4
rm coverage.out.5
rm coverage.out.6
rm coverage.out.7
rm coverage.out.8
rm coverage.out.9