name: Go Build Test
on: [push]
jobs:

  go-redis-action:
    name: go-redis-action
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Redis
      uses: zhulik/redis-action@v1.0.0
      with:
        redis version: latest

    - name: Test Origin Redis
      run: GO_REDIS_PORT=:6379 go test ./...

    - name: Test Self
      run: GO_REDIS_PORT=:9091 go test ./...
